kidzy_frais:
    resource: "@KidzyBundle/Resources/config/routing/frais.yml"
    prefix:   /frais
kidzy_packs:
    resource: "@KidzyBundle/Resources/config/routing/pack.yml"
    prefix:   /packs
kidzy_classe:
    resource: "@ClasseBundle/Resources/config/routing/classe.yml"
    prefix:   /classes

kidzy_enfants:
    resource: "@KidzyBundle/Resources/config/routing/enfant.yml"
    prefix:   /enfants

kidzy_gardes:
    resource: "@KidzyBundle/Resources/config/routing/garde.yml"
    prefix:   /gardes
kidzy_homepage:
    path:     /
    defaults: { _controller: KidzyBundle:Default:index }