event_index:
    path:     admin/
    defaults: { _controller: "KidzyBundle:Event:index" }
    methods:  GET
event_show:
    path:     admin/{idEvent}/show
    defaults: { _controller: "KidzyBundle:Event:show" }
    methods:  GET
event_new:
    path:     admin/new
    defaults: { _controller: "KidzyBundle:Event:new" }
    methods:  [GET, POST]
event_edit:
    path:     admin/{idEvent}/edit
    defaults: { _controller: "KidzyBundle:Event:edit" }
    methods:  [GET, POST]
event_delete:
    path:     admin/{idEvent}/delete
    defaults: { _controller: "KidzyBundle:Event:delete" }
    methods:  DELETE
event:
    path:     /events
    defaults: { _controller: "KidzyBundle:Event:event" }
    methods:  GET
eventParent:
    path:     /liste
    defaults: { _controller: KidzyBundle:event:indexParent}